FROM oven/bun:1

WORKDIR /app
COPY src/frontend/package.json src/frontend/bun.lockb ./
RUN bun install --frozen-lockfile

COPY src/frontend .

EXPOSE 5173
CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
